
const nodemailer = require("nodemailer");
const { google } = require("googleapis");
const OAuth2 = google.auth.OAuth2;


const oauth2Client = new OAuth2(
     "1069745389480-ptglqmdp168fnod1ss6crq0pac0oar3i.apps.googleusercontent.com", // ClientID
     "d__qYjB10VHdTHBSuIPMXbFb", // Client Secret
     "https://developers.google.com/oauthplayground" // Redirect URL
);


oauth2Client.setCredentials({
     refresh_token: "1//04mhCqzpTxeemCgYIARAAGAQSNwF-L9Ir4q7QehvOrUapux8sim3uRjsdVveU0IrWt2FRbOFF3d8iBJSUvtUNJJEuOU0sWnVpBN8"
});
const accessToken = oauth2Client.getAccessToken()


const smtpTransport = nodemailer.createTransport({
     service: "gmail",
     auth: {
          type: "OAuth2",
          user: "rajathm64@gmail.com", 
          clientId: "1069745389480-ptglqmdp168fnod1ss6crq0pac0oar3i.apps.googleusercontent.com",
          clientSecret: "d__qYjB10VHdTHBSuIPMXbFb",
          refreshToken: "1//04mhCqzpTxeemCgYIARAAGAQSNwF-L9Ir4q7QehvOrUapux8sim3uRjsdVveU0IrWt2FRbOFF3d8iBJSUvtUNJJEuOU0sWnVpBN8",
          accessToken: accessToken
     }
});


tls: {
  rejectUnauthorized: false
}


const mailOptions = {
     from: "rajathm64@gmail.com",
     to: "ganeshhanuman89@gmail.com",
     subject: "Node.js Email with Secure OAuth",
     generateTextFromHTML: true,
     html: "<b>This is an Autogenerated mail sent by bot 123 do not reply</b>"
};



smtpTransport.sendMail(mailOptions, (error, response) => {
     error ? console.log(error) : console.log(response);
     smtpTransport.close();
});





